package api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"time"

	"github.com/schnoddelbotz/cloud-vm-docker/task"
)

// client for HTTP CFN endpoint
// TODO:
// func (c *Client) Delete(task) err
// func (c *Client) GetStatus(task_id) (Task, err)
// func (c *Client) ListTasks() (Tasks, err)

// The client should also be usable as curl alternative for containers to report status/progress
// idea: if nothing was reported back, try to fetch last line of stackdriver output of container -> FireStore.LastMsg

// CFNClient holds infos required to act as client to cloud-vm-docker HTTP cloud function
type CFNClient struct {
	Endpoint    string
	AccessToken string
	HTTPClient  *http.Client
}

// NewCFNClient gives a new client for followup CloudFunction requests
func NewCFNClient(endpoint, accessToken string) *CFNClient {
	client := &CFNClient{
		Endpoint:    endpoint,
		AccessToken: accessToken,
	}
	client.HTTPClient = &http.Client{
		//CheckRedirect: func(req *http.Request, via []*http.Request) error {
		//	return http.ErrUseLastResponse
		//},
	}
	return client
}

// GetEndpoint returns the HTTP URL of deployed CloudVMDocker CloudFunction, based on project and region
func GetEndpoint(project, region string) string {
	if project == "" {
		log.Fatalf("Cannot create CFN HTTP Client without --project")
	}
	if region == "" {
		log.Fatalf("Cannot create CFN HTTP Client without --region")
	}
	return fmt.Sprintf("https://%s-%s.cloudfunctions.net/CloudVMDocker", region, project)
}

// Run submits a Docker task to run in the cloud to HTTP CloudFunction endpoint
func (c *CFNClient) Run(taskArgs task.TaskArguments) (task.Task, error) {
	log.Printf("CFNClient/Run endpoint: %s", c.Endpoint)
	log.Printf("CFNClient/Run image   : %s", taskArgs.Image)
	log.Printf("CFNClient/Run command : %q", taskArgs.Command)
	log.Printf("CFNClient/Run VM type : %s | Non-default subnet: '%s' | Tags: %s",
		taskArgs.VMType, taskArgs.Subnet, taskArgs.Tags)
	requestBody, err := json.Marshal(taskArgs)
	if err != nil {
		log.Fatalf("Error building requests JSON: %s", err)
	}
	requestPath := fmt.Sprintf("run/%s/%s", taskArgs.VMID, taskArgs.VMType)
	responseBody, err := c.executeClientRequest("POST", requestPath, requestBody)
	if err != nil {
		log.Fatalf("Error submitting request: %s", err)
	}
	var task task.Task
	err = json.Unmarshal(responseBody, &task)
	if err != nil {
		log.Printf("Unmarshalling response failed: %s", err)
	}
	log.Printf("SUCCESS: Created task vm: %s (instanceID %s)", task.VMID, task.InstanceID)
	return task, nil
}

func (c *CFNClient) WaitForDoneStatus(vmID string) task.Task {
	var myTask task.Task
	status := "unknown"
	requestPath := fmt.Sprintf("status/%s/", vmID)
	// todo: vm-myTask create --wait used firestore realtime updates
	//       ...  any way to delegate to firestore API "web" endpoints, using auth token generated by CFN?
	log.Printf("Waiting for DONE status of VM %s", vmID)
	for status != task.TaskStatusDone {
		body, err := c.executeClientRequest("GET", requestPath, []byte{})
		if err != nil {
			log.Fatalf("ClientERR: %s", err)
		}
		err = json.Unmarshal(body, &myTask)
		if err != nil {
			log.Fatalf("Client JSON ERR: %s", err)
		}
		if status != myTask.Status {
			log.Printf("Status change: %s -> %s", status, myTask.Status)
		}
		status = myTask.Status
		if status != task.TaskStatusDone {
			time.Sleep(30 * time.Second) // FIXME make configurable ... or switch also to non-polling
		}
	}
	log.Printf("SUCCESS waiting for DONE status of VM %s", vmID)
	return myTask
}

func (c *CFNClient) executeClientRequest(method, path string, requestBody []byte) ([]byte, error) {
	url := fmt.Sprintf("%s/%s", c.Endpoint, path)
	requestBodyReader := bytes.NewReader(requestBody)
	request, err := http.NewRequest(method, url, requestBodyReader)
	if err != nil {
		log.Fatalf("Client failed: %s", err)
		return []byte{}, err
	}
	request.Header.Set("X-Authorization", c.AccessToken)
	request.Header.Set("Content-type", "application/json")

	response, err := c.HTTPClient.Do(request)
	if err != nil {
		log.Fatalf("Client failed: %s", err)
	}
	if response.StatusCode != 200 {
		// log.Printf("Client got non-200 response: %d", response.StatusCode)
		// 302: redirect by google to auth page, if CFN is not deployed or not public
		return nil, fmt.Errorf("error: Non-200 response %d from %s", response.StatusCode, url)
	}
	responseBody, err := ioutil.ReadAll(response.Body)
	return responseBody, err
}
